name: Check
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  check-firefox-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make firefox
      - run: git diff --exit-code
